# Generated by Django 5.0.1 on 2024-03-02 02:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Products of gamming console', null=True),
        ),
    ]
