# Generated by Django 5.0.1 on 2024-03-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_products_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products'),
        ),
    ]
