# Generated by Django 5.0.1 on 2024-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cartorders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorders',
            name='order_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
