# Generated by Django 5.0.1 on 2024-03-03 02:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrderTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.cartorders')),
            ],
            options={
                'verbose_name_plural': 'Cart Order Total',
            },
        ),
    ]
