# Generated by Django 5.0.1 on 2024-03-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_cartordertotal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.cartorders'),
        ),
    ]
