# Generated by Django 5.0.1 on 2024-03-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_cartorders_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='100.20', max_digits=999999999999),
        ),
    ]
