# Generated by Django 5.0.1 on 2024-03-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_cartordertotal_order_cartordertotal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorders',
            name='final_amount',
        ),
    ]
