# Generated by Django 5.0.1 on 2024-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_cartorders_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartordertotal',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
