# Generated by Django 5.0.1 on 2024-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_cartordertotal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartordertotal',
            name='status',
            field=models.BooleanField(),
        ),
    ]
