# Generated by Django 5.0.1 on 2024-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_cartordertotal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartordertotal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
