# Generated by Django 5.0.1 on 2024-03-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_cartordertotal_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
