# Generated by Django 5.0.1 on 2024-03-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_myorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myorders',
            options={'verbose_name_plural': 'My Order'},
        ),
    ]
